name: AshlynSurvival
version: '${project.version}'
main: nl.ashlyn.ashlynsurvival.AshlynSurvival
api-version: 1.19
authors: [ Ashlyn ]
description: Custom plugin for my SMP Server that I run for my friends
commands:
  hat:
    description: Stylish
    usage: /hat
  coords:
    description: Sends player's coords
    usage: /coords
  bccoords:
    description: Broadcasts player's coords
    usage: /bcoords
  herstart:
    description: Restart server
    usage: /herstart
  spawn:
    description: Tp to Spawn
    usage: /spawn
  sethome:
    description: Set players home.
    usage: /sethome
  home:
    description: tps player to set home.
    usage: /home